CREATE DATABASE INVENTORY_STRUCTURE
USE INVENTORY_STRUCTURE

-- CREATING ALL THE REQUIRED TABLES
CREATE TABLE SUPPLIER
(SIDS CHAR(5) NOT NULL, SNAME VARCHAR(30) NOT NULL, 
SADD VARCHAR(50) NOT NULL, SCITY VARCHAR(10) DEFAULT 'DELHI',
SPHONE CHAR(15) UNIQUE, SEMAIL VARCHAR(30), PRIMARY KEY(SIDS))


USE INVENTORY_STRUCTURE
SELECT * FROM SUPPLIER

CREATE TABLE PRODUCT
(PID CHAR(5) NOT NULL, PDESC VARCHAR(200) NOT NULL, 
PRICE INT NOT NULL CHECK(PRICE>0),
CATEGORY VARCHAR(20) NOT NULL CHECK(CATEGORY IN ('LAPTOP','ACCESSORIES','DESKTOP','MONITOR')),
SIDS CHAR(5) REFERENCES SUPPLIER(SIDS))

ALTER TABLE PRODUCT 
ADD CONSTRAINT PKPID PRIMARY KEY(PID)

SELECT * FROM PRODUCT

CREATE TABLE STOCK
(PID CHAR(5) REFERENCES PRODUCT(PID),SQTY INT CHECK(SQTY>=0),
ROL INT CHECK(ROL>0), MOQ INT CHECK(MOQ>=5))

SELECT * FROM STOCK

CREATE TABLE CUST
(CID CHAR(5) NOT NULL, CNAME VARCHAR(30) NOT NULL,
CADDRESS VARCHAR(50) NOT NULL,CCITY VARCHaR(10) NOT NULL,
CPHONE CHAR(15) NOT NULL, CEMAIL VARCHAR(30) NOT NULL,
DOB DATE CHECK(DOB<'01 JAN, 2000'), PRIMARY KEY(CID))

SELECT * FROM CUST

CREATE TABLE ORDERS 
(OID CHAR(5) NOT NULL, ODATE DATE, 
CID CHAR(5) REFERENCES CUST(CID),
PID CHAR(5) REFERENCES PRODUCT(PID), 
OQTY INT CHECK(OQTY >= 1))

SELECT * FROM SUPPLIER
SELECT * FROM PRODUCT
SELECT * FROM STOCK
SELECT * FROM CUST
SELECT * FROM ORDERS

USE INVENTORY_STRUCTURE

-- CREATING ID FUNCTION FOR AOTOMATED GENERATION OF IDS FOR ALL THE TABLES
CREATE FUNCTION INVEN_ID (@IDC AS CHAR(1), @I AS INT)
RETURNS CHAR(5)	
AS
BEGIN
	DECLARE @ID AS CHAR(5)
	IF @I < 10 
		SET @ID = CONCAT(@IDC,'000',@I)
	ELSE IF @I < 100
		SET @ID = CONCAT(@IDC,'00',@I)
	ELSE IF @I < 1000
		SET @ID = CONCAT(@IDC,'0',@I)
	ELSE IF @I < 10000
		SET @ID = CONCAT(@IDC,@I)
	ELSE 
		SET @ID = 'NA'
	RETURN @ID
END;

-- CREATING PROCEDURE FOR SUPPLIER TABLE
CREATE SEQUENCE SUPP_SEQ
AS INT
START WITH 1
INCREMENT BY 1;

CREATE PROCEDURE INSUPP  @SN AS VARCHAR(30), @SAD AS VARCHAR(30), @SC AS VARCHAR(20), @SP AS CHAR(15), @SE AS VARCHAR(30)
AS
BEGIN 
	DECLARE @I AS INT
	DECLARE @ID AS CHAR(5)

	SET @I = (NEXT VALUE FOR SUPP_SEQ)
	SET @ID = DBO.INVEN_ID('S',@I)
	INSERT INTO SUPPLIER
	VALUES (@ID,@SN,@SAD,@SC,@SP,@SE)

	SELECT * FROM SUPPLIER

END;

-- CREATING PROCEDURE FOR PRODUCT TABLE
CREATE SEQUENCE PROD_SEQ
AS INT
START WITH 1
INCREMENT BY 1;

CREATE PROCEDURE INPROD  @PDES AS VARCHAR(200), @P AS INT, @CAT AS VARCHAR(20),@SID AS CHAR(5)
AS
BEGIN 
	DECLARE @I AS INT
	DECLARE @ID AS CHAR(5)

	SET @I = (NEXT VALUE FOR PROD_SEQ)
	SET @ID = DBO.INVEN_ID('P',@I)
	INSERT INTO PRODUCT
	VALUES (@ID,@PDES,@P,@CAT,@SID)

	SELECT * FROM PRODUCT

END;

-- CREATING PROCEDURE FOR STOCK TABLE

CREATE PROCEDURE INSTOCK @PID AS CHAR(5), @SQTY AS INT, @ROL AS INT, @MOQ AS INT
AS
BEGIN 
	INSERT INTO STOCK
	VALUES (@PID,@SQTY,@ROL,@MOQ)

	SELECT * FROM STOCK

END;

-- CREATING PROCEDURE FOR CUST TABLE
CREATE SEQUENCE CUST_SEQ
AS INT
START WITH 1
INCREMENT BY 1;


CREATE PROCEDURE INCUST @CN AS VARCHAR(30), @CAD AS VARCHAR(30), @CC AS VARCHAR(15), @CP AS CHAR(15), @CE AS VARCHAR(30), @DOB AS DATE
AS 
BEGIN
	DECLARE @I AS INT
	DECLARE @ID AS CHAR(5)

	SET @I = (NEXT VALUE FOR CUST_SEQ)
	SET @ID = DBO.INVEN_ID('C',@I)

	INSERT INTO CUST
	VALUES(@ID,@CN,@CAD,@CC,@CP,@CE,@DOB)

	SELECT * FROM CUST
END;

-- CREATING PROCEDURE FOR ORDERS TABLE
CREATE SEQUENCE ORD_SEQ
AS INT
START WITH 1
INCREMENT BY 1;

CREATE PROCEDURE INORDERS @CID AS CHAR(5),@PID AS CHAR(5), @OQTY AS INT
AS 
BEGIN
	DECLARE @OI AS INT
	DECLARE @OID AS CHAR(5)
	
	SET @OI = (NEXT VALUE FOR ORD_SEQ)
	SET @OID = DBO.INVEN_ID('O',@OI)

	INSERT INTO ORDERS
	VALUES(@OID,GETDATE(),@CID,@PID,@OQTY)

	SELECT * FROM ORDERS
END;

-- CREATING TRIGGER FOR AUTOMATED UPDATION OF STOCK QUANTITY WHENEVER AN ORDER IS PLACED
CREATE TRIGGER TR_IN_ORD
ON ORDERS 
FOR INSERT
AS
BEGIN
	UPDATE STOCK SET SQTY = SQTY - (SELECT OQTY FROM INSERTED)
	WHERE PID = (SELECT PID FROM INSERTED)

END;


-- CREATING TRIGGER FOR AUTOMATED UPDATION OF STOCK QUANTITY WHENEVER AN ORDER IS CANCELLED
CREATE TRIGGER TR_UP_ORD
ON ORDERS
FOR DELETE
AS 
BEGIN
	UPDATE STOCK SET SQTY = SQTY + (SELECT OQTY FROM DELETED)
	WHERE PID = (SELECT PID FROM DELETED)

END;

-- CREATING TRIGGER TO AUTOMATED CHECKING OF THE STOCK QUANTITY BEFORE ACCEPTING THE ORDER
CREATE TRIGGER TR_CHECK_STOCK
ON ORDERS
FOR INSERT
AS 
BEGIN
	DECLARE @OQ AS INT
	DECLARE @SQ AS INT

	SET @OQ = (SELECT OQTY FROM INSERTED)
	SET @SQ = (SELECT SQTY FROM STOCK WHERE PID = (SELECT PID FROM INSERTED))

	IF @SQ >= @OQ
				BEGIN
					UPDATE STOCK SET SQTY = @SQ - @OQ
					WHERE PID = (SELECT PID FROM INSERTED)
					
					COMMIT;
				END
	ELSE 
		PRINT('ORDER CANCELLED DUE TO INSUFFICIENT STOCK')
		ROLLBACK
END;

-- CREATING TRIGGER FOR AUTOMATED UPDATION OF STOCK QUANTITY AFTER THE UPDATION OF ORDER QUANTITY
CREATE TRIGGER TR_UPD_ORD
ON ORDERS
FOR UPDATE
AS
BEGIN
	UPDATE STOCK SET SQTY = SQTY + (SELECT OQTY FROM DELETED)
	WHERE PID = (SELECT PID FROM DELETED)

	UPDATE STOCK SET SQTY = SQTY - (SELECT OQTY FROM INSERTED)
	WHERE PID = (SELECT PID FROM INSERTED)

END;


-- INSERTING RECORDS IN SUPPLIER TABLE
INSUPP 'RAJESH KUMAR', 'RK DIST., SECTOR 11', 'DELHI','8418048465','RKD@GMAIL.COM';
INSUPP 'ABRAR MUSTAFA', 'ABRAR AND SONS, CHANDNI CHOWK','DELHI','9418481839','ABRARM_A_N_S@GMAIL.COM';
INSUPP 'AJAY DHALIWAL', 'DHALIWAL DISTRIBUTIONS, LAHORI GATE', 'PUNJAB', '7168059593','DHALIWALDIST@GMAIL.COM';
INSUPP 'CHAMPAK TRIPATHI', 'TRIPATHI ELECTRONICS, SECTOR 27','NOIDA', '8484801814','TRIPATHIELEC.@GMAIL.COM';
INSUPP 'MANOJ SHARMA','SHARMA ELECTRONICS, RAJPUR ROAD','DEHRADUN','8764684976','MJ_ELECTRONICS@OUTLOOK.COM';
INSUPP 'WASEEM PATHAN','TECH. SOLUTIONS, SECTOR 18', 'NOIDA', '9518438180', 'WASEEM18@GMAIL.COM';
INSUPP 'SURINDER SINGH','A-Z SOLUTIONS, KHAN MARKET', 'DELHI', '7108950455','A_ZSOLUTION@GMAIL.COM';
INSUPP 'JASPAL ARORA','ELECTRONICS MART, SECTOR 2','NOIDA','8408468699','JA_ELECTRONICS@GMAIL.COM';
INSUPP 'VIJAY KUMAR','VIJAY SALES, CONNAUGHT PLACE','DELHI','9084849441','VIJAYSALES@OUTLOOK.COM';
INSUPP 'AMIR KHAN','KHAN E-COLLECTIONS, LAJPAT NAGAR CENTRAL','DELHI','9809480583','KE_COLL@GMAIL.COM';

SELECT * FROM SUPPLIER


-- INSERTING RECORDS IN PRODUCT TABLE
INPROD 'HP PAVILLION GAMING LAPTOP, AMD RYZEN 4800H 16 GB RAM 4 GB GRAPHICS CARD(NVIDIA GTX 1650TI) 1TB HDD 256 GB SSD',75000,'LAPTOP','S0006';
INPROD 'ALIENWARE AURORA R15 GAMING, INTEL CORE i9 13900KF, 32GB 4800MHz RAM, 1TB HDD, 512 NVMe SSD, 24GB GC(NVIDIA RTX 4090), ',575000,'DESKTOP','S0008'
INPROD 'DELL 27 QHD MONITOR, 27'' QHD 2560 x 1440 AT 75Hz',25000,'MONITOR','S0001';
INPROD 'AMERICAN TOURISTER SPIN 49CMS BLACK LAPTOP BAG ',1800,'ACCESSORIES','S0006';
INPROD 'LOGITECH WIRELESS MOUSE B170',600,'ACCESSORIES','S0002';
INPROD 'MACBOOK AIR LAPTOP M2 CHIP, 13.6 INCH RETINA DISPLAY, 8GB RAM 256GB SSD, BACKLIT KEYBOARD, 1080P FACETIME HD CAMERA',111000,'LAPTOP','S0010';
INPROD 'DELL USB WIRELESS KEYBOARD AND MOUSE SET- KM3322W',1400,'ACCESSORIES','S0002';
INPROD 'SAMSUNG 81CM UHD (4K)HIGH RESOLUTION WITH IPS PANEL AND DCI-P3 98%, HDR600 AND USB TYPE-C',46500,'MONITOR','S0003';

SELECT * FROM PRODUCT

-- INSERTING RECORDS IN STOCK TABLE
INSTOCK 'P0001',50,5,10;
INSTOCK 'P0002',25,2,5;
INSTOCK 'P0003',70,5,5;
INSTOCK 'P0004',100,5,10;
INSTOCK 'P0005',100,10,20;
INSTOCK 'P0006',75,10,10;
INSTOCK 'P0007',100,20,10;
INSTOCK 'P0008',40,2,5;

SELECT * FROM STOCK

-- INSERTING RECORDS IN CUSTUMERS TABLE
INCUST 'DHARMENDRA SINGH','CHANDNI CHOWK','DELHI','9509862695','DHARMENDRASINGH@GMAIL.COM','09 SEP, 1990';
INCUST 'ABDULLAH SAYYAD','SECTOR 11','NOIDA','8081819925','SAYYADABDULLAH123@GMAIL.COM','10 JAN, 1995';
INCUST 'GOPAL VARMA','SECTOR 9','DELHI','8468409596','GOPALVARMA@OUTLOOK.COM','25 MAR,1999';
INCUST 'RAM KAPOOR','AJINKYA SOCIETY, SECTOR 27','NOIDA','7890849562','RK100@GMAIL.COM','12 APR, 1988';
INCUST 'ZABI KHAN','HOUSE NO. 144, BLOCK 11','DEHRADUN','9502553480','ZK101@GMAIL.COM','30 JUN, 1997';
INCUST '','','','','','';



CREATE VIEW BILL
AS 
SELECT ORDERS.OID, ODATE, CNAME, CADDRESS, CPHONE, PDESC, PRICE, OQTY, PRICE*OQTY AS 'AMOUNT'
FROM ORDERS 
INNER JOIN CUST 
ON ORDERS.CID = CUST.CID
INNER JOIN PRODUCT
ON ORDERS.PID = PRODUCT.PID

SELECT * FROM BILL


